### ISSUE TITLE
Publish to the PowerShell Gallery

### ISSUE THREAD

**Issue by daviwil** [jimmehc/PowerBash#1]
Hey, cool module!  I think people would find this pretty helpful.  Would you publish this to the PowerShell Gallery?  All you need is to create a module manifest (`PowerBash.psd`) with `New-ModuleManifest`, create an account on powershellgallery.com and then use the `Publish-Module` command.  You'll need the NuGet API key that you'll find in your user account once you register.  Let me know if you have any questions about how to do that.

**Comment by jimmehc** [comment]
Done.  I put PromptEd up too.
